version: '2.1'

services:
  selenium:
    extends:
      file: docker-compose.base.yml
      service: selenium
    depends_on:
      - chrome
      - firefox

  chrome:
    extends:
      file: docker-compose.base.yml
      service: chrome
    environment:
      # These are legacy compose links env vars that the image is relying on.
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium

  firefox:
    extends:
      file: docker-compose.base.yml
      service: firefox
    environment:
      # These are legacy compose links env vars that the image is relying on.
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_PORT_4444_TCP_ADDR=selenium
